config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :books, only: [:new, :create, :index, :show, :edit, :update, :destroy]
  resources :users, only: [:index, :show, :edit, :update]

  get "/home/about" => "homes#about", as: "about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  validates :title, presence: true
  validates :body, length: { maximum: 200}
  validates :body, presence: true

  def get_image
    if image.attached?
      image
    else
      'no_image.jpg'
    end
  end

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

  has_one_attached :profile_image

  validates :name, presence: true
  validates :name, length: { minimum: 2, maximum: 20}
  validates :name, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top,:about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resouse)
    flash[:notice] = "Signed in successfully."
    user_path(current_user.id)
  end

  def after_sign_out_path_for(resouse)
    flash[:notice] = "Signed out successfully."
    "/"
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      flash[:notice] = "You have created book failed."
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def index
    @books = Book.all
    @user = current_user
    @book = Book.new
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @book_new = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
     if @book.update(book_params)
        flash[:notice] = "You have updated book successfully."
        redirect_to book_path(@book.id)
     else
        flash[:notice] = "You have updated book failed."
        render :edit
     end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to '/books'
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def is_matching_login_user
    book = Book.find(params[:id])
    user_id = book.user_id
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to '/books'
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update]
  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
       flash[:notice] = "You have created book successfully."
       redirect_to user_path(@user.id)
    else
      render:edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
<h2>Editing Book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
  <label for="inputTitle">Title</label>
  <%= f.text_field :title, autofocus: true, id:"inputTitle", placeholder:"Title"%>
  <label for="inputOpinion">Opinion</label>
  <%= f.text_area :body, placeholder: "inputOpinion", placeholder:"Opinion" %>
  <%= f.submit "Update Book" %>
<% end %>

<h3>
  <% if @book.user == current_user %>
    <%= link_to "Show", book_path(@book) %>
  <% end %>
  <% if @book.user == current_user %>
    <%= link_to "Back", "/books" %>
  <% end %>
</h3>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <div>
     <%= render 'users/user', user: @user ,book: @book %>
   </div>
 </div>

  <div class="col-md-8 offset-md-1">
    <table class="table table-striped">
    <h1>Books</h1>
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
       <% @books.each do |book| %>
        <tr>
          <td>
          <%= link_to user_path(book.user.id) do %>
          <%= image_tag book.user.get_profile_image(100,100) %>
          <% end %>
          </td>
          <td><%= link_to book.title, book_path(book.id) %></td>
          <td><%= book.body %></td>
        </tr>
        <% end %>
     </tbody>
    </table>
  </div>
 </div>
</div>

app/views/books/new.html.erb
<h1>New Book</h1>
<% if @book.errors.any? %>
  <%= @book.errors.count %>件のerrorが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
    <h4>Title</h4>
      <%= f.text_field :title  %>
    <h4>Opinion</h4>
      <%= f.text_area :body %>
    <%= f.submit 'Create Book' %>
<% end %>

app/views/books/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <div>
     <%= render 'users/user', user: @user, book: @book_new %>
   </div>
 </div>

  <div class="col-md-8 offset-md-1">
    <table class="table table-striped">
    <h1>Book detail</h1>
     <thead>
      <tr></tr>
     </thead>
     <tbody>
        <tr>
          <td>
          <%= link_to (@book.user) do %>
          <%= image_tag @book.user.get_profile_image(100,100) %> </br>
          <%= @book.user.name %>
          <% end %>
          </td>
          <td>
           <%=link_to @book.title, book_path(@book.id) %>
          </td>
          <td><%= @book.body %></td>
          <td>
           <% if @book.user == current_user %>
           <%= link_to "Edit", edit_book_path(@book.id), class:"btn btn-success" %>
           <% end %>
          </td>
          <td>
           <% if @book.user == current_user %>
           <%= link_to "Destroy", book_path(@book), method: :delete, class:"btn btn-danger" %>
           <% end %>
          </td>
        </tr>
     </tbody>
    </table>
  </div>
 </div>
</div>

app/views/homes/about.html.erb
<h1>Welcome to<i class='fas fa-book'></i>Bookers!</h1>

app/views/homes/top.html.erb
<div>
  <%= flash[:notice] %>
</div>
<h1><strong>welcome to <i class='fas fa-book'></i> Bookers !!</strong></h1>
<p>
  In <strong><i class='fas fa-book'></i>Bookers</strong>, <br />
  you can share and exchange your opinions, inpressions, and emotions <br />
  about various books!
</p>

<%= link_to 'Log in', "/users/sign_in", class:"btn btn-primary" %>
<%= link_to 'Sign up', "/users/sign_up", class:"btn btn-success" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <a class="navbar-brand" href="/", class: 'nav-link text-white' >
            <span>Bookers</span>
          </a>
           <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
           </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <i class='fas fa-home'>
              <%= link_to "Home", user_path(current_user.id), class: 'nav-link text-white' %>
            </i>
            <i class='fas fa-users'>
              <%= link_to "Users", "/users", class: 'nav-link text-white' %>
            </i>
            <i class='fas fa-book-open'>
              <%= link_to "Books", "/books", class: 'nav-link text-white' %>
            </i>
            <i class='fas fa-sign-out-alt'>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: 'nav-link text-white' %>
            </i>
            <% else %>
            <i class='fas fa-home'>
              <%= link_to "Home", "/", class: 'nav-link text-white' %>
            </i>
            <i class='fas fa-link'>
              <%= link_to "About", "/home/about", class: 'nav-link text-white' %>
            </i>
            <i class='fas fa-user-plus'>
              <%= link_to "Sign up", new_user_registration_path, class: 'nav-link text-white' %>
            </i>
            <i class='fas fa-sign-in-alt'>
              <%= link_to "Log in", new_user_session_path, class: 'nav-link text-white' %>
            </i>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="container mt-5">
      <div class="container">
        <div class="row">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>
          </div>
        </div>
      </div>
    </footer>
  </body>
</html>

app/views/users/_user.html.erb
<h1>User info</h1>
<%= image_tag user.get_profile_image(100,100) %>
<p>name：<%= user.name %></p>
<p>introduction : <%= user.introduction %></p>
<%= link_to edit_user_path(user) do %>
<p class="btn btn-outline-secondary btn-block">
  <i class='fas fa-user-cog'></i>
</p>
<% end %>

<h1>New book</h1>
<%= form_with model: book do |f| %>
<h4>Title</h4>
<%= f.text_field :title %>
<h4>Opinion</h4>
<%= f.text_area :body %>
<%= f.submit 'Create Book', class:"btn btn-success" %>

<% end %>

app/views/users/edit.html.erb
<div>
  <%= flash[:notice] %>
</div>

<h2>User info</h2>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @user do |f| %>
  <label for="inputName">Name</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"名前"%>
  <label for="inputImage">Image</label>
  <%= f.file_field :profile_image, placeholder: "画像", accept: "image/*" %>
  <label for="inputIntroduction">Introduction</label>
  <%= f.text_area :introduction, autofocus: true, id:"inputIntroduction" %>
  <%= f.submit "Update User" %>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <div>
   <%= render 'user', user: @user, book: @book %>
   </div>
  </div>

  <div class="col-md-8 offset-md-1">
    <table class="table table-striped">
    <h1>Users</h1>
     <thead>
      <tr>
       <th>image</th>
       <th>name</th>
       <th></th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
       <% @users.each do |user| %>
        <tr>
        <%= link_to user_path(user.id) do %>
          <td><%= image_tag user.get_profile_image(100,100) %>
          </td>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user %></td>
          <% end %>
        </tr>
        <% end %>
     </tbody>
    </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<div>
  <%= flash[:notice] %>
</div>
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <div>
     <%= render 'user', user: @user, book: @book %>
   </div>
 </div>

  <div class="col-md-8 offset-md-1">
    <table class="table table-striped">
    <h1>Books</h1>
     <thead>
      <tr>
       <th></th>
       <th>Title</th>
       <th>Opinion</th>
       <th colspan="3"></th>
      </tr>
     </thead>
     <tbody>
       <% @books.each do |book| %>
        <tr>
         <td>
         <%= link_to user_path(@user.id) do %>
         <%= image_tag book.user.get_profile_image(100,100) %>
         <% end %>
         </td>
         <td><%=link_to book.title, book_path(book.id) %></td>
         <td><%= book.body %></td>
        </tr>
        <% end %>
     </tbody>
    </table>
  </div>
 </div>
</div>